name: Applying features
on: [push]
jobs:
  Feast-apply:
    runs-on: self-hosted
    steps:
      - run: echo "Start applying features into Feast"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: cd ./in_bug
      - run: feast apply
      - run: feast materialize-incremental $(date -u +"%Y-%m-%dT%H:%M:%S")
      - run: echo "ğŸ This job's status is ${{ job.status }}."

